
const silly = [
    'twerk',
    'aaaaaaaaaa',
    'shadup',
    'Are you my mommy?',
    'u stinky',
    "Once I got stuck in a Blizzard and it was cold.",
    'hello Luanti',
    null,
    'beep boop',
    'I ate a crayon',
    'Where are my pants?',
    'I’m a potato',
    'Let’s dance like spaghetti',
    'Pew pew!',
    'Can I borrow your socks?',
    'Bath time in the ocean!',
    'Banana for president!',
    'Oops, I licked the screen',
    'Who put cheese in my keyboard?',
    'Don’t trust ducks',
    'I sniff glue (but the legal kind)',
    'Everything is lava',
    'Cow says moo but I say WAAAH',
    'It’s Tuesday somewhere',
    'I’m typing with my nose',
    'Can’t stop won’t stop spinning',
    'I put my goldfish in charge',
    'Ice cream is a soup if you wait long enough',
    'My socks are political',
    'All hail the rubber chicken',
    'I dream of pickles',
    'I put pants on my cat and hats on my gat',
    'CHAOS IS A LIFESTYLE',
    'Did someone say beans?',
    'I bark at my neighbors',
    'Slap the keyboard for luck',
    "It's 9PM somewhere.",
    "Time for you to get a watch",
    "caca",
    'Toes are just finger cousins',
    'My coffee ran away',
    'E equals MC-sneeze',
    'I’ve seen things… mostly squirrels',
    'The moon owes me money',
    'One brain cell and it’s on vacation',
    'I wrote a poem about spaghetti',
    'Never trust a penguin in a tuxedo',
    'Too many buttons, not enough tacos',
    'I named my fridge Karen',
    'Reality is optional',
    'I’m allergic to homework',
    'I once yelled at a tree',
    'I have no idea what I’m doing',
    'This is my final form',
    'I play chess with pigeons',
    'My microwave is judging me',
    'Socks are just foot prisons',
    'I’m 70% caffeine',
    'I lick batteries for energy',
    'Behold! My awkward power!',
    'I am a spoon in a world of forks',
    'Math is a government conspiracy',
    'I live in a simulation coded by raccoons',
    'I eat cereal with a fork to save milk',
    'Beans. Just beans.',
    'My cat has a PhD in chaos',
    'I traded my brain for spaghetti',
    'Life’s a glitch',
    'Keyboard smash supremacy!',
    'I identify as tired',
    'Do robots have nightmares?',
    'I scream, you scream, we all existentially scream',
    'Did someone unplug my brain?',
    'Gravity is optional today',
    'I bring chaos and snacks',
    'Shouting into the void!',
    'I’m a walking oops',
    'Certified silly goose',
    'Loading... Please wait...',
    'My ideas have side effects',
    'Too many thoughts, not enough dance',
    'I pet rocks professionally',
    'Fried logic with a side of nonsense',
    'My shadow left me',
    'Caution: unmedicated imagination',
    'Reality.exe has crashed',
    'flagrant wearer',
    "Sometimes I eat with my mouth open and you can't stop me",
    'I yawn in Morse code',
    'Blink twice for pizza',
    'My hat is a portal',
    'I run on pure weird',
    'Toaster squad unite!',
    'Oops, I dropped the universe',
    'My laugh echoes in another dimension',
    'I sneeze glitter',
    'Wiggle wiggle boom',
    'Soup is just hot wet food',
    'I speak fluent chaos',
    'Brain sold separately',
    'Welcome to my Ted talk about cheese',
    'I told my shoes a secret',
    'Can I eat the moon?',
    'Ping me when logic returns',
    "Life is like a box of chocolates. You never know what you're gonna get.",
    'my name: scooter. your name: dumbhead.',
    'my wife left me for a lifetime supply of tunafish sandwiches',
    'ok boomer',
];

const extremetoaster = [
    'Just because someone called rat wanted to blow my house so much that he put 1 million nukes in it',
    'im sad for im noob i dont ave armor',
    'pls armor in nether and blood sword',
    'ME REPORTE YOU NOW',
    'STOP',
    'IM ADMIN',
    'stop or me reporte you for spawnkilling',
    'you can giveme a wings plis',
    'im here for modding purposes',
    'Get inside now; I will ban you if you don’t',
]


const animals = [
    "woof", "meow", "quack", "moo", "baa", "neigh", "oink", "ribbit", "buzz", "hiss",
    "roar", "chirp", "tweet", "caw", "growl", "howl", "cluck", "bleat", "croak", "snort",
    "squeak", "bark", "purr", "honk", "coo", "hoot", "snarl", "whinny", "screech", "gobble",
    "warble", "yowl", "trill", "bray", "click", "drum", "squawk", "bellow", "huff", "peep",
    "grunt", "yap", "mew", "chirrup", "gurgle", "hum", "whimper", "shriek", "pant", "whistle",
    "meep", "nya", "arf", "yiff", "eeek", "squee", "eep", "blub", "cackle", "sniff",
    "thrum", "nicker", "twit-twoo", "grrr", "chirble", "bloop", "dook", "rawr", "cooo", "cheep",
    "keek", "yarp", "woooo", "nyaa", "nyaan", "bork", "nyoom", "squeee", "eep-eep", "screeb",
    "wark", "graww", "reee", "snurk", "tweep", "twirp", "gyaaa", "fweep", "hurk", "meorw",
    "pew", "shree", "meugh", "fwip", "glerk", "blep", "mrow", "boof", "wheeze", "cchirp"
];;

const all = silly.concat(animals).concat(extremetoaster)

module.exports = {
    silly,
    animals,
    all,
}